### PR TITLE
Deployment and environment configuration documentation

### PR DESCRIPTION
**Pull request by matt6697**
- Improved readme to describe how to setup the environment.
- Added pre requisties
- Added FRRouting and Citrix ADC deployment guide.

### CODE REVIEW

**Comment by matt6697** [comment]
Hi @jpmondet, could you tell me if the readme is understandable and if you manage to get a working environment when following the readme steps ?

**Comment by jpmondet** [comment]
Hello !

Yeah, I'm a bit overwhelmed right now but I'll try to review this if I happen to find some time during the WE :)

**Comment by jpmondet** [comment]
Hello !

Had a couple of issues (mostly typos, I'm preparing a MR for this but it will have to wait till next week-end) but the show-stopper to me was that I'm denied when I'm trying to pull the `store/citrix/citrixadccpx:13.0-36.29` image.  
Do you have a special dockerhub account ?

**Comment by matt6697** [comment]
You have to go on the Citric ADC 13.0 dockerhub page and fill in a Citrix
registration form before being able to docker pull the
store/citrix/citrixadccpx:13.0-36.29 image

**Pull request merged**
